## numpy

References: <br>
E-book: Python for Data Analysis, 2nd Edition

In [3]:
import numpy as np

### 1. 创建ndarray

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [5]:
np.linspace(-1, 1, 10)

array([-1.        , -0.77777778, -0.55555556, -0.33333333, -0.11111111,
        0.11111111,  0.33333333,  0.55555556,  0.77777778,  1.        ])

In [17]:
np.random.rand(1)

array([0.45978601])

In [18]:
np.random.randn(3,4)

array([[-0.79556999,  0.36421339,  1.41933929, -0.50470795],
       [ 0.09181817,  1.01892793,  0.18923656,  0.9224496 ],
       [ 0.92512886,  0.14116579,  0.87265088, -0.00378922]])

In [11]:
np.random.randint(10)

4

In [15]:
np.random.randint(2,6)

4

In [16]:
np.random.randint(0,100, (3,4))

array([[78, 43, 47, 79],
       [65,  0, 49, 40],
       [ 3, 82,  0,  3]])

In [21]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
np.empty((3,3))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 6.22522714e-321],
       [1.15706964e-306, 2.33419537e-312, 0.00000000e+000]])

In [4]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

np.array(): Convert input data (list, tuple, array, or other sequence type) to an ndarray either by inferring a dtype or explicitly specifying a dtype; copies the input data by default

In [21]:
data = [[1,2,3],[4,5,6],[7,8,9]]
arr2d = np.array(data)

In [32]:
arr2d.shape

(3, 3)

In [34]:
arr2d.ndim

2

In [22]:
arr2d.dtype

dtype('int32')

In [23]:
arr2d.argmax()

8

In [62]:
arr2d.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [65]:
arr2d[1:,1:]

array([[5, 6],
       [8, 9]])

In [57]:
arr1 = np.array([1,2,3,4])
arr2 = np.ones(4)

In [58]:
print(arr1, arr2)

[1 2 3 4] [1. 1. 1. 1.]


In [59]:
arr1 + arr2

array([2., 3., 4., 5.])

In [60]:
arr1 * 2

array([2, 4, 6, 8])

In [89]:
arr1 * arr2

array([1., 2., 3., 4.])

In [91]:
arr1.dot(arr2)

10.0

In [92]:
arr1 @ arr2

10.0

In [30]:
data = np.arange(32).reshape(8, 4)
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [33]:
data.sum()

496

In [34]:
# axis = 0, sum by row data
data.sum(axis=0)

array([112, 120, 128, 136])

In [35]:
# asis = 1, sum by column data
data.sum(axis=1)

array([  6,  22,  38,  54,  70,  86, 102, 118])

In [36]:
data.mean()

15.5

In [38]:
np.unique(data)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [53]:
arr1 = np.arange(12).reshape(3,4)
arr2 = np.random.randn(3, 4)
print(f"arr1:\n{arr1}\narr2:\n{arr2}")

arr1:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
arr2:
[[-0.01489152  0.55913396  1.48792955  0.23217942]
 [ 0.64216833  0.27428822 -0.84619437  0.30162671]
 [ 2.59947925 -1.59655237  2.2184053  -0.82202568]]


In [54]:
arr1 + 2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [57]:
arr1 - arr2

array([[ 0.01489152,  0.44086604,  0.51207045,  2.76782058],
       [ 3.35783167,  4.72571178,  6.84619437,  6.69837329],
       [ 5.40052075, 10.59655237,  7.7815947 , 11.82202568]])

In [59]:
arr1.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [62]:
arr1 * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])